"""autogenerated by genpy from lab5_msgs/GUIPointMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import lab5_msgs.msg

class GUIPointMsg(genpy.Message):
  _md5sum = "88fef43974ed58433a24c05c8e4d27fd"
  _type = "lab5_msgs/GUIPointMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 x
float64 y
int64 shape
ColorMsg color
================================================================================
MSG: lab5_msgs/ColorMsg
int64 r
int64 g
int64 b
"""
  __slots__ = ['x','y','shape','color']
  _slot_types = ['float64','float64','int64','lab5_msgs/ColorMsg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,shape,color

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GUIPointMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.shape is None:
        self.shape = 0
      if self.color is None:
        self.color = lab5_msgs.msg.ColorMsg()
    else:
      self.x = 0.
      self.y = 0.
      self.shape = 0
      self.color = lab5_msgs.msg.ColorMsg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2d4q.pack(_x.x, _x.y, _x.shape, _x.color.r, _x.color.g, _x.color.b))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.color is None:
        self.color = lab5_msgs.msg.ColorMsg()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.x, _x.y, _x.shape, _x.color.r, _x.color.g, _x.color.b,) = _struct_2d4q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2d4q.pack(_x.x, _x.y, _x.shape, _x.color.r, _x.color.g, _x.color.b))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.color is None:
        self.color = lab5_msgs.msg.ColorMsg()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.x, _x.y, _x.shape, _x.color.r, _x.color.g, _x.color.b,) = _struct_2d4q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2d4q = struct.Struct("<2d4q")
