"""autogenerated by genpy from gc_msgs/GCServoMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GCServoMsg(genpy.Message):
  _md5sum = "0da8e84971f583398e0e97d0e835b4ee"
  _type = "gc_msgs/GCServoMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 frontTrackFractionOn
float64 backTrackFractionOn
float64 hamperFractionOpen

"""
  __slots__ = ['frontTrackFractionOn','backTrackFractionOn','hamperFractionOpen']
  _slot_types = ['float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frontTrackFractionOn,backTrackFractionOn,hamperFractionOpen

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GCServoMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.frontTrackFractionOn is None:
        self.frontTrackFractionOn = 0.
      if self.backTrackFractionOn is None:
        self.backTrackFractionOn = 0.
      if self.hamperFractionOpen is None:
        self.hamperFractionOpen = 0.
    else:
      self.frontTrackFractionOn = 0.
      self.backTrackFractionOn = 0.
      self.hamperFractionOpen = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3d.pack(_x.frontTrackFractionOn, _x.backTrackFractionOn, _x.hamperFractionOpen))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.frontTrackFractionOn, _x.backTrackFractionOn, _x.hamperFractionOpen,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3d.pack(_x.frontTrackFractionOn, _x.backTrackFractionOn, _x.hamperFractionOpen))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.frontTrackFractionOn, _x.backTrackFractionOn, _x.hamperFractionOpen,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3d = struct.Struct("<3d")
