"""autogenerated by genpy from gc_msgs/KinectMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class KinectMsg(genpy.Message):
  _md5sum = "330b0cbd839da82abf2a23fd0978d352"
  _type = "gc_msgs/KinectMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 blockHeading
bool blockSeen
"""
  __slots__ = ['blockHeading','blockSeen']
  _slot_types = ['float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       blockHeading,blockSeen

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(KinectMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.blockHeading is None:
        self.blockHeading = 0.
      if self.blockSeen is None:
        self.blockSeen = False
    else:
      self.blockHeading = 0.
      self.blockSeen = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_dB.pack(_x.blockHeading, _x.blockSeen))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.blockHeading, _x.blockSeen,) = _struct_dB.unpack(str[start:end])
      self.blockSeen = bool(self.blockSeen)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_dB.pack(_x.blockHeading, _x.blockSeen))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.blockHeading, _x.blockSeen,) = _struct_dB.unpack(str[start:end])
      self.blockSeen = bool(self.blockSeen)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_dB = struct.Struct("<dB")
