/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/rss-student/rss-2014-team-3/src/lab5_msgs/msg/GUILineMsg.msg
 *
 */


#ifndef LAB5_MSGS_MESSAGE_GUILINEMSG_H
#define LAB5_MSGS_MESSAGE_GUILINEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <lab5_msgs/ColorMsg.h>

namespace lab5_msgs
{
template <class ContainerAllocator>
struct GUILineMsg_
{
  typedef GUILineMsg_<ContainerAllocator> Type;

  GUILineMsg_()
    : lineA(0.0)
    , lineB(0.0)
    , lineC(0.0)
    , color()  {
    }
  GUILineMsg_(const ContainerAllocator& _alloc)
    : lineA(0.0)
    , lineB(0.0)
    , lineC(0.0)
    , color(_alloc)  {
    }



   typedef double _lineA_type;
  _lineA_type lineA;

   typedef double _lineB_type;
  _lineB_type lineB;

   typedef double _lineC_type;
  _lineC_type lineC;

   typedef  ::lab5_msgs::ColorMsg_<ContainerAllocator>  _color_type;
  _color_type color;




  typedef boost::shared_ptr< ::lab5_msgs::GUILineMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab5_msgs::GUILineMsg_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct GUILineMsg_

typedef ::lab5_msgs::GUILineMsg_<std::allocator<void> > GUILineMsg;

typedef boost::shared_ptr< ::lab5_msgs::GUILineMsg > GUILineMsgPtr;
typedef boost::shared_ptr< ::lab5_msgs::GUILineMsg const> GUILineMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab5_msgs::GUILineMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab5_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'lab5_msgs': ['/home/rss-student/rss-2014-team-3/src/lab5_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab5_msgs::GUILineMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab5_msgs::GUILineMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab5_msgs::GUILineMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ee858aa33ac4230e8ab893c71e571e8";
  }

  static const char* value(const ::lab5_msgs::GUILineMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ee858aa33ac4230ULL;
  static const uint64_t static_value2 = 0xe8ab893c71e571e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab5_msgs/GUILineMsg";
  }

  static const char* value(const ::lab5_msgs::GUILineMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 lineA\n\
float64 lineB\n\
float64 lineC\n\
ColorMsg color\n\
================================================================================\n\
MSG: lab5_msgs/ColorMsg\n\
int64 r\n\
int64 g\n\
int64 b\n\
";
  }

  static const char* value(const ::lab5_msgs::GUILineMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lineA);
      stream.next(m.lineB);
      stream.next(m.lineC);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GUILineMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab5_msgs::GUILineMsg_<ContainerAllocator>& v)
  {
    s << indent << "lineA: ";
    Printer<double>::stream(s, indent + "  ", v.lineA);
    s << indent << "lineB: ";
    Printer<double>::stream(s, indent + "  ", v.lineB);
    s << indent << "lineC: ";
    Printer<double>::stream(s, indent + "  ", v.lineC);
    s << indent << "color: ";
    s << std::endl;
    Printer< ::lab5_msgs::ColorMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB5_MSGS_MESSAGE_GUILINEMSG_H
