(cl:defpackage gc_msgs-msg
  (:use )
  (:export
   "<MOTORCOMMANDMSG>"
   "MOTORCOMMANDMSG"
   "<POSEMSG>"
   "POSEMSG"
   "<HAMPERMSG>"
   "HAMPERMSG"
   "<GCSERVOMSG>"
   "GCSERVOMSG"
   "<CONVEYORMSG>"
   "CONVEYORMSG"
   "<BUMPMSG>"
   "BUMPMSG"
   "<ENCODERMSG>"
   "ENCODERMSG"
   "<OBSTACLEAHEADMSG>"
   "OBSTACLEAHEADMSG"
   "<MOTIONMSG>"
   "MOTIONMSG"
   "<WHEELVELOCITYMSG>"
   "WHEELVELOCITYMSG"
  ))

