(cl:in-package gc_msgs-msg)
(cl:export '(FRONTTRACKFRACTIONON-VAL
          FRONTTRACKFRACTIONON
          BACKTRACKFRACTIONON-VAL
          BACKTRACKFRACTIONON
          HAMPERFRACTIONOPEN-VAL
          HAMPERFRACTIONOPEN
))